version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=
      - REDIS_URI=
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=
      - REDIS_HOST=
      - REDIS_PORT=16422
      - JWT_SECRET=your_jwt_secret
      - ADMIN_PASSWORD=your_admin_password
      - NODE_ENV=production
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: